name: Build and Push All Docker Images to GHCR

on:
  push:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '**/*.sh'
      - .github/workflows/ghcr-monorepo-matrix.yml
  workflow_dispatch:

jobs:
  discover-contexts:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-matrix.outputs.images }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: bash
        run: |
          images=$(find . -type f -name Dockerfile | xargs -n1 dirname | sed 's|^\./||' | jq -R . | jq -sc .)
          echo "images=$images" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover-contexts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ${{ fromJson(needs.discover-contexts.outputs.images) }}
      fail-fast: false

    permissions:
      contents: read
      packages: write

    env:
      GH_IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase directory/image name
        id: lower-name
        run: |
          IMAGE_NAME=$(basename "${{ matrix.context }}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9._-' '-' | sed 's/[-._]*$//')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.context }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          tags: |
            ${{ env.GH_IMAGE_PREFIX }}/${{ steps.lower-name.outputs.IMAGE_NAME }}:latest
            ${{ env.GH_IMAGE_PREFIX }}/${{ steps.lower-name.outputs.IMAGE_NAME }}:${{ github.sha }}